workspace:
  base: /go
  path: src/github.com/wasilak/kubernetes_exporter

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get -t ./...
      - go build -o $GOPATH/bin/kubernetes_exporter-$GOOS-$GOARCH *.go

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
       - /go/bin/kubernetes_exporter-*
    when:
      event: tag

matrix:
  GOPATH:
    - /go

  GO_VERSION:
    - latest

  GOARCH:
    - amd64
    - 386

  GOOS:
    - linux
    - darwin
    - windows
